### ISSUE TITLE
Broken link in Readme.md

### ISSUE THREAD

**Issue by ArminJo** [arduino/library-registry-submission-parser#27]
The link https://github.com/arduino/library-registry is broken,

**Comment by per1234** [comment]
Thanks @ArminJo! The repository was set to private mode as we worked on getting it in shape for use for submitting libraries. It is now public and the link will be accessible to everyone.

Announcement here: https://blog.arduino.cc/2021/06/07/new-workflow-for-arduino-library-submissions/
